services:
  postgres:
    image: postgres:16
    container_name: team2-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: eclipse-temurin:25-jdk
    container_name: team2-backend
    working_dir: /app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - gradle-cache:/root/.gradle
      - gradle-project-cache:/app/.gradle
    environment:
      # NB! konteineris DB host = postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

    command: ["sh", "-lc", "chmod +x ./gradlew && ./gradlew bootRun --no-daemon"]

volumes:
  pgdata:
  gradle-cache:
  gradle-project-cache:
